// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcmmcljpmknmjjswyidq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbW1jbGpwbWtubWpqc3d5aWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njg2OTgsImV4cCI6MjA2OTA0NDY5OH0.bAoLdSz82JS-vygMPZ-FEgyY10Wh4UJggP2HxHcr-2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});